### ISSUE TITLE
Entity requires @Entity when it is declared with @KeySpace

### ISSUE THREAD

**Issue by JustinCRL** [spring-projects/spring-data-keyvalue#541]
Reading https://docs.spring.io/spring-data/keyvalue/docs/current/reference/html/#key-value.keyspaces or https://www.baeldung.com/spring-data-key-value it seems that you do not need @Entity however I get an the following error with H2 as my repository

2023-10-21T10:17:06.706-05:00 INFO 3536 --- [ main] .RepositoryConfigurationExtensionSupport : Spring Data Map - Could not safely identify store assignment for repository candidate interface com.example.demo.sql.Repo; If you want this repository to be a Map repository, consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository

I am using Java 17 with Spring Boot 3.1.5

Code: https://github.com/JustinCRL/spring-data-keyvalue
StackOverflow: https://stackoverflow.com/questions/77336626/why-is-enitity-required-for-keyspace-enitity-for-spring-data-keyvalue

**Comment by JustinKSU** [comment]
Confirmed it doesn't work in 3.2.0-SNAPSHOT either.

**Comment by jxblum** [comment]
Why are you [declaring](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/pom.xml#L24-L27) Spring Data KeyValue as a dependency, but then [use](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/pom.xml#L21-L23) Spring Data JPA?

First, Spring Data KeyValue is not meant to be used directly as a Spring Data store implementation.

As [described](https://github.com/spring-projects/spring-data-keyvalue#spring-data-keyvalue---), the Spring Data KeyValue module and framework provides a common abstraction for Key/Value stores, such as **Redis** using [Spring Data Redis](https://spring.io/projects/spring-data-redis), or **Hazelcast** using [Spring Data Hazelcast](https://github.com/hazelcast/spring-data-hazelcast#spring-data-hazelcast). In other words, Spring Data KeyValue builds on the core concepts and foundation from Spring Data (Commons) for Key/Value stores specifically.

> NOTE: While Spring Data KeyValue "provides" a `Map` implementation ([here](https://github.com/spring-projects/spring-data-keyvalue/tree/main/src/main/java/org/springframework/data/map), and [specifically](https://github.com/spring-projects/spring-data-keyvalue/blob/main/src/main/java/org/springframework/data/map/MapKeyValueAdapter.java#L39-L43)) of the Spring Data Commons `CrudRepository` interface and DAO abstraction ([Javadoc](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)), it is not intended to be used as your Spring Boot/Data application's DAO. It is useful, perhaps, for limited testing purposes.

However, because this "Map" implementation was provided by Spring Data KeyValue (in your Spring Boot/Data application classpath), you have entered "**multi-module**" mode (see [documentation](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.multiple-modules)).

Now, you must explicitly declare and distinguish, precisely which persistent entity is mapped to which underlying data store (an RDBMS, as you have [configured](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/pom.xml#L28-L32), along with [this](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/src/main/resources/application.properties), or the cheap, Map-based implementation provided by SD KeyValue; I am certain you wanted **H2** in your case).

As described in [documentation](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.multiple-modules), this is done by either 1) declaring an ("identifying") mapping annotation on your application persistent entity types or 2) declaring your `Repository` interface to extend a Spring Data module-specific `CrudRepository` type, such as `JpaRepository` from Spring Data JPA.

> NOTE: The `@KeySpace` entity annotation is not enough by itself to make this distinction, unlike Spring Data module-specific "mapping" annotations, such as JPA's `@Entity` annotation for SD JPA, or the `@Document` annotation for SD MongoDB, or the `@RedisHash` annotation for Spring Data Redis, and so on.

> TIP: This is apparent in the SD module, store-specific implementation of `RepositoryConfigurationExtension`, overridden `getIdentifyingAnnotations()` method; for [example](https://github.com/spring-projects/spring-data-redis/blob/3.2.0-RC1/src/main/java/org/springframework/data/redis/repository/configuration/RedisRepositoryConfigurationExtension.java#L134-L137), in Spring Data Redis, unlike SD KeyValue's `RepositoryConfiguraitonExtension` ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/3.2.0-RC1/src/main/java/org/springframework/data/keyvalue/repository/config/KeyValueRepositoryConfigurationExtension.java#L69)), which does not declare any "identifying" annotations, only identifying (_Repository_) types ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/3.2.0-RC1/src/main/java/org/springframework/data/keyvalue/repository/config/KeyValueRepositoryConfigurationExtension.java#L68-L71)).

So, in fact, because your application `Repo` extends the "generic" (non-store specific, Spring Data Commons) `CrudRepository`, you do (!) need to declare the JPA `@Entity` annotation on your application, persistent entity class (`KeyValue`, [source](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/src/main/java/com/example/demo/sql/KeyValue.java)) in order to clarify which underlying data store will persist and store your entity.

**Comment by jxblum** [comment]
To be clear, you can either 

1) (_Recommended_) Keep your `Repo` definition as is, [extending](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/src/main/java/com/example/demo/sql/Repo.java#L6) `CrudRepository<KeyValue, String>`, and simply annotate your `KeyValue` entity class with JPA's `@Entity` annotation, as you have done [before](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/src/main/java/com/example/demo/sql/KeyValue.java#L8). So...

Given:

```java
@Entity
public KeyValue { 
  // ...
}
```

And:

```java
public interface Repo extends CrudRepository<KeyValue, String> { }
```

Then:

```java
@SpringBootApplication
@EntityScan(basePackageClasses = KeyValue.class)
@EnableJpaRepositories(basePackageClasses = Repo.class)
public class DemoApplication {

  // ...

}
```

2) Alternatively, you can (keeping all else the same, i.e. `@KeySpace` on `KeyValue`, and `@EnableMapRepositories` on your `DempApplication` class, as you have [done](https://github.com/JustinCRL/spring-data-keyvalue/blob/master/src/main/java/com/example/demo/sql/Repo.java#L6)):

```java
public interface Repo extend KeyValueRepository<KeyValue, String> { }
```

But arguably, in the context of JPA, `@EnableMapRepositories` and `@KeySpace` annotations from Spring Data KeyValue make no sense.

**Comment by JustinKSU** [comment]
That makes a lot of sense.  We have Spring Data JPA is a dependency for
other reasons.  Thanks for this extensive explanation.

**Comment by jxblum** [comment]
You are welcome. Good luck!
