### ISSUE TITLE
Add minimal keyspace bound interface to access underlying store via Adapter. [DATAKV-103]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-keyvalue#81]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAKV-103](https://jira.spring.io/browse/DATAKV-103?redirect=false)** and commented

Introduce `KeyValueStore` abstraction offering basic put/get/count/remove operations without usage of template.

Should be based upon `KeyValueAdapter` so one still can make use of the underlying abstraction. Access should be available via `KeyValueOperations`

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-keyvalue/pull/9

**Comment by jxblum** [comment]
Not sure what the original intent of this "enhancement" was, but it does not seem to align with the direction and intended use of Spring Data, and more generally, Spring, since the "_Template_" pattern is the common way to interface with the underlying data store.

Also closing because this is really old.
